services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: marches-publics-backend
    networks:
      - gov
  client:
    build:
      context: .
      dockerfile: ui/Dockerfile
    image: marches-publics-frontend
    ports:
      - "80:80"
    networks:
      - gov

networks:
  gov: