name: Deployment

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Inject environment
        run: |
          envsubst < .env.prod > .env
        shell: bash
        env:
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASS: ${{ secrets.MONGO_PASS }}
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          MONGO_NAME: ${{ secrets.MONGO_NAME }}
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/marches-publics
            git pull origin main
            docker build -f Dockerfile -t marches-publics-backend .
            cd ui && docker build -f Dockerfile -t marches-publics-frontend .
            docker-compose up --detach