name: Deployment

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        env:
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASS: ${{ secrets.MONGO_PASS }}
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          MONGO_NAME: ${{ secrets.MONGO_NAME }}
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ vars.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/marches-publics
            sudo git pull
            sudo envsubst < .env.prod > .env
            sudo docker build -f Dockerfile -t marches-publics-backend .
            cd ui && sudo docker build -f Dockerfile -t marches-publics-frontend .
            cd /var/www/marches-publics
            sudo docker-compose down
            sudo docker-compose up --detach