name: Deploy React and Flask App

on:
  push:
    branches:
      - main # Ou la branche que vous utilisez pour le déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Connexion au serveur via SSH et déploiement
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }} # Supprimez cette ligne si vous utilisez le port 22
          script: |
            cd /chemin/vers/votre/application
            git pull origin main
            # Backend : Installation des dépendances et démarrage
            cd backend
            pip install -r requirements.txt
            flask run --host=0.0.0.0 & # Adaptez selon votre configuration de déploiement
            # Frontend : Construction et déploiement
            cd ../frontend
            npm install
            npm run build
            # Utilisez la commande appropriée pour redémarrer votre serveur web ou votre processus de backend ici, si nécessaire
